name = "clubtaps"
main = "src/index.js"
compatibility_date = "2026-09-25"

[[d1_databases]]
binding = "DB"
database_name = "clubtaps-db"
database_id = "828edf68-3d35-4618-a060-bba37c3b228b"

[[routes]]
pattern = "clubtaps.com/*"
zone_name = "clubtaps.com"

[[routes]]
pattern = "www.clubtaps.com/*"
zone_name = "clubtaps.com"

[observability]
enabled = true
